export { default as Navigation } from './Navigation';
export { default as HeroSection } from './HeroSection';
export { default as AboutSection } from './AboutSection';
export { default as ExperienceSection } from './ExperienceSection';
export { default as ProjectsSection } from './ProjectsSection';
export { default as CertificatesSection } from './CertificatesSection';
export { default as EducationSection } from './EducationSection';
export { default as ContactSection } from './ContactSection';
export { default as Footer } from './Footer';
